spring.application.name: nexwork-api
server.port: 8081

budgets.host: ${BUDGETS_API_URI:http://localhost:8085/budgets/v1/}
contracts.host: ${CONTRACTS_API_URI:http://localhost:8084/contracts/v1/}
accounts.host: ${ACCOUNTS_API_URI:http://localhost:8083/accounts/v1/}

logging:
  level:
    root: INFO
    ar.edu.unlam.tpi.nexwork_api: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %logger{36} - %msg%n"